# Generated by Django 3.1 on 2021-12-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='image1',
        ),
        migrations.AddField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(default=1, max_length=255, upload_to='store/products'),
            preserve_default=False,
        ),
    ]
